name: planif
description: "Aplicación de calendario académico con arquitectura MVVM y Clean Architecture"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Gestión de estado
  flutter_riverpod: ^2.6.1
  
  # Base de datos local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilidades
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Generador de código para Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
